"use server";
import { useTranslation } from "@/app/i18n";

export default async function ({
  params: { lng },
}: {
  params: {
    lng: string;
  };
}) {
  const { t } = await useTranslation(lng, "faq");

  return (
    <div className="text-white w-[75%] mx-auto py-16">
      <p>
        <strong>{t("1")}</strong>
      </p>
      <p>
        <strong>
          {t("2")}
        </strong>
      </p>
      <p>
        <span>
          {t("3")}
        </span>
      </p>
      <p>
        <strong>{t("4")}:</strong>
      </p>
      <p>
        <span>● {t("5")}</span>
      </p>
      <p>
        <span>● {t("6")}</span>
      </p>
      <p>
        <span>● {t("7")}</span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>
          {t("8")}
        </strong>
      </p>
      <p>
        <span>
          {t("9")}:
        </span>
      </p>
      <p>
        <span>
          ●&nbsp;{t("10")}
        </span>
      </p>
      <p>
        <span>● {t("11")}</span>
      </p>
      <p>
        <span>● {t("12")}</span>
      </p>
      <p>
        <span>• {t("13")}:</span>
      </p>
      <p>
        <span>● {t("14")}</span>
      </p>
      <p>
        <span>● {t("15")}</span>
      </p>
      <p>
        <span>● {t("16")}</span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>{t("17")}</strong>
      </p>
      <p>
        <span>
          {t("18")}:
        </span>
      </p>
      <p>
        <span>● {t("19")}</span>
      </p>
      <p>
        <span>● {t("20")}</span>
      </p>
      <p>
        <span>● {t("21")}</span>
      </p>
      <p>&nbsp;</p>
      <p>
        <span>
          {t("22")}:
        </span>
      </p>
      <p>
        <span>
          {t("23")}:
        </span>
      </p>
      <p>
        <span>● {t("24")}</span>
      </p>
      <p>
        <span>
          ● {t("25")}
        </span>
      </p>
      <p>
        <span>● {t("26")}</span>
      </p>
      <p>
        <span>● {t("27")}</span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>
          {t("28")}
        </strong>
      </p>
      <p>
        <span>
          {t("29")}:
        </span>
      </p>
      <p>
        <span>● {t("20")}</span>
      </p>
      <p>
        <span>● {t("31")}</span>
      </p>
      <p>
        <span>● {t("32")}</span>
      </p>
      <p>
        <span>● {t("33")}</span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>
          {t("34")}
        </strong>
      </p>
      <p>
        <span>
        {t("35")}&nbsp;
        </span>
        <strong>{t("36")}</strong>
        <span>
          &nbsp;{t("37")}&nbsp;
        </span>
        <strong>{t("38")}</strong>
        <span>&nbsp;{t("39")}</span>
      </p>
      <p>
        <strong>{t("40")}</strong>
      </p>
      <p>
        <span>
        {t("41")}:
        </span>
      </p>
      <p>
        <span>● {t("42")}</span>
      </p>
      <p>
        <span>● {t("43")}</span>
      </p>
      <p>
        <span>● {t("44")}</span>
      </p>
      <p>
        <span>● {t("45")}</span>
      </p>
      <p>
        <span>● {t("46")}</span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>
          {t("47")}
        </strong>
      </p>
      <p>
        <span>{t("48")}&nbsp;</span>
        <strong>{t("49")}</strong>
        <span>
          &nbsp;{t("50")}&nbsp;
        </span>
        <strong>{t("51")}</strong>
        <span>&nbsp;{t("52")}</span>
      </p>
      <p>
        <strong>
        {t("53")}
        </strong>
      </p>
      <p>
        <span>
        {t("54")}:
        </span>
      </p>
      <p>
        <span>● {t("55")}</span>
      </p>
      <p>
        <span>● {t("56")}</span>
      </p>
      <p>
        <span>●&nbsp;{t("57")}</span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>
        {t("58")}
        </strong>
      </p>
      <p>
        <span>
        {t("59")}
        </span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>&nbsp;</strong>
      </p>
      <p>
        <strong>&nbsp;</strong>
      </p>
      <p>
        <strong>
        {t("60")}
        </strong>
      </p>
      <p>
        <span>{t("62")}</span>
        <strong>&nbsp;</strong>
        <span>
        {t("62")}
        </span>
      </p>
      <p>
        <strong>
        {t("63")}
        </strong>
      </p>
      <p>
        <span>
        {t("64")}
        </span>
      </p>
      <p>
        <strong>{t("65")}</strong>
      </p>
      <p>
        <span>
        {t("66")}
        </span>
      </p>
      <p>
        <strong>
        {t("67")}
        </strong>
      </p>
      <p>
        <span>{t("68")}</span>
      </p>
      <p>
        <span>
          ● {t("69")}
        </span>
      </p>
      <p>
        <span>● {t("70")}</span>
      </p>
      <p>
        <span>● {t("71")}</span>
      </p>
      <p>
        <span>
          ● {t("72")}
        </span>
      </p>
      <p>
        <span>
          ● {t("73")}
        </span>
      </p>
      <p>
        <span>
          ● {t("74")}
        </span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>{t("75")}</strong>
      </p>
      <p>
        <span>
        {t("76")}
        </span>
      </p>
      <p>
        <strong>
        {t("77")}
        </strong>
      </p>
      <p>
        <span>
        {t("78")}
        </span>
      </p>
      <p>
        <strong>
        {t("79")}
        </strong>
      </p>
      <p>
        <span>
        {t("80")}
        </span>
      </p>
      <p>
        <strong>
        {t("81")}
        </strong>
      </p>
      <p>
        <span>
        {t("82")}
        </span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>
        {t("83")}
        </strong>
      </p>
      <p>
        <span>
        {t("84")}
        </span>
      </p>
      <p>
        <strong>
        {t("85")}
        </strong>
      </p>
      <p>
        <span>
        {t("86")}
        </span>
      </p>
      <p>
        <strong>
        {t("87")}
        </strong>
      </p>
      <p>
        <span>
        {t("88")}
        </span>
      </p>
      <p>
        <strong>{t("89")}</strong>
      </p>
      <p>
        <span>
        {t("90")}
        </span>
      </p>
      <p>
        <strong>{t("91")}</strong>
      </p>
      <p>
        <span>
        {t("92")}
        </span>
      </p>
      <p>
        <strong>
        {t("93")}
        </strong>
      </p>
      <p>
        <span>{t("94")}:</span>
      </p>
      <p>
        <span>● {t("95")}</span>
      </p>
      <p>
        <span>● {t("96")}</span>
      </p>
      <p>
        <span>● {t("97")}</span>
      </p>
      <p>
        <span>● {t("98")}</span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>{t("99")}</strong>
      </p>
      <p>
        <span>
        {t("100")}
        </span>
      </p>
      <p>
        <strong>
        {t("101")}
        </strong>
      </p>
      <p>
        <span>
        {t("102")}
        </span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>&nbsp;</strong>
      </p>
      <p>
        <strong>
        {t("103")}
        </strong>
      </p>
      <p>
        <span>
        {t("104")}
        </span>
      </p>
      <p>
        <strong>
        {t("105")}
        </strong>
      </p>
      <p>
        <span>
        {t("106")}
        </span>
      </p>
      <p>
        <strong>
        {t("107")}
        </strong>
      </p>
      <p>
        <span>
        {t("108")}
        </span>
      </p>
      <p>
        <strong>
        {t("109")}
        </strong>
      </p>
      <p>
        <span>
        {t("110")}
        </span>
      </p>
      <p>
        <strong>
        {t("111")}
        </strong>
      </p>
      <p>
        <span>
        {t("112")}
        </span>
      </p>
      <p>
        <strong>
        {t("113")}
        </strong>
      </p>
      <p>
        <span>
        {t("114")}
        </span>
      </p>
      <p>
        <strong>
        {t("115")}
        </strong>
      </p>
      <p>
        <span>
        {t("116")}
        </span>
      </p>
      <p>
        <strong>
        {t("117")}
        </strong>
      </p>
      <p>
        <span>
        {t("118")}
        </span>
      </p>
      <p>
        <strong>
        {t("119")}
        </strong>
      </p>
      <p>
        <span>
          {t("185")}
        </span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>
        {t("120")}
        </strong>
      </p>
      <p>
        <span>
        {t("121")}
        </span>
      </p>
      <p>
        <strong>{t("122")}</strong>
      </p>
      <p>
        <span>
        {t("123")}
        </span>
      </p>
      <p>
        <strong>
        {t("124")}
        </strong>
      </p>
      <p>
        <span>
        {t("125")}
        </span>
      </p>
      <p>
        <strong>
        {t("126")}
        </strong>
      </p>
      <p>
        <span>
        {t("127")}
        </span>
      </p>
      <p>
        <strong>
        {t("128")}
        </strong>
      </p>
      <p>
        <span>
        {t("129")}
        </span>
      </p>
      <p>
        <strong>
        {t("130")}
        </strong>
      </p>
      <p>
        <span>
        {t("131")}
        </span>
      </p>
      <p>
        <strong>
        {t("132")}
        </strong>
      </p>
      <p>
        <span>
        {t("133")}
        </span>
      </p>
      <p>
        <strong>
        {t("134")}
        </strong>
      </p>
      <p>
        <span>
        {t("135")}
        </span>
      </p>
      <p>
        <strong>
        {t("136")}
        </strong>
      </p>
      <p>
        <span>
        {t("137")}
        </span>
      </p>
      <p>
        <strong>
        {t("138")}
        </strong>
      </p>
      <p>
        <span>
        {t("139")}
        </span>
      </p>
      <p>
        <strong>
        {t("140")}
        </strong>
      </p>
      <p>
        <span>
        {t("141")}
        </span>
      </p>
      <p>
        <strong>
        {t("142")}
        </strong>
      </p>
      <p>
        <span>
        {t("143")}
        </span>
      </p>
      <p>
        <strong>
        {t("144")}
        </strong>
      </p>
      <p>
        <span>
        {t("145")}
        </span>
      </p>
      <p>
        <strong>
        {t("146")}
        </strong>
      </p>
      <p>
        <span>
        {t("147")}
        </span>
      </p>
      <p>
        <strong>
        {t("148")}
        </strong>
      </p>
      <p>
        <span>
        {t("149")}
        </span>
      </p>
      <p>
        <strong>
        {t("150")}
        </strong>
      </p>
      <p>
        <span>
        {t("151")}
        </span>
      </p>
      <p>
        <strong>
        {t("152")}
        </strong>
      </p>
      <p>
        <span>
        {t("153")}
        </span>
      </p>
      <p>
        <strong>
        {t("154")}
        </strong>
      </p>
      <p>
        <span>
        {t("155")}
        </span>
      </p>
      <p>
        <strong>
        {t("156")}
        </strong>
      </p>
      <p>
        <span>
        {t("157")}
        </span>
      </p>
      <p>
        <strong>&nbsp;</strong>
      </p>
      <p>
        <strong>
        {t("158")}
        </strong>
      </p>
      <p>
        <span>
        {t("159")}
        </span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>
        {t("160")}
        </strong>
      </p>
      <p>
        <span>
        {t("161")}
        </span>
      </p>
      <p>&nbsp;</p>
      <p>
        <strong>
        {t("162")}
        </strong>
      </p>
      <p>
        <span>
        {t("163")}
        </span>
      </p>
      <p>
        <strong>
        {t("164")}
        </strong>
      </p>
      <p>
        <span>
        {t("165")}
        </span>
      </p>
      <p>
        <strong>
        {t("166")}
        </strong>
      </p>
      <p>
        <span>
        {t("167")}
        </span>
      </p>
      <p>
        <strong>
        {t("168")}
        </strong>
      </p>
      <p>
        <span>
        {t("169")}
        </span>
      </p>
      <p>
        <strong>
        {t("170")}
        </strong>
      </p>
      <p>
        <span>
        {t("171")}
        </span>
      </p>
      <p>
        <strong>
        {t("172")}
        </strong>
      </p>
      <p>
        <span>
        {t("173")}
        </span>
      </p>
      <p>
        <strong>
        {t("174")}
        </strong>
      </p>
      <p>
        <span>
        {t("175")}
        </span>
      </p>
      <p>
        <strong>
        {t("176")}
        </strong>
      </p>
      <p>
        <span>
        {t("177")}
        </span>
      </p>
      <p>
        <strong>
        {t("178")}
        </strong>
      </p>
      <p>
        <span>
        {t("179")}
        </span>
      </p>
      <p>
        <strong>
        {t("180")}
        </strong>
      </p>
      <p>
        <span>
        {t("181")}
        </span>
      </p>
      <p>
        <strong>
        {t("182")}
        </strong>
      </p>
      <p>
        <span>
        {t("183")}
        </span>
      </p>
      <p>
        <span>
        {t("184")}
        </span>
      </p>
      <p>&nbsp;</p>
      <p>&nbsp;</p>
      <p>&nbsp;</p>
      <p>&nbsp;</p>
    </div>
  );
}
